// Between-session events, revealed to players via a direct link (never linked from the site nav).
// Add one entry per event. `id` is used in the URL as event.html?id=<id> and must be unique.
// `image` is the path to the image inside events/images/. `text` is a list of paragraphs/lines.
const EVENTS = [
  {
    id: "the-rattening",
    title: "The Rattening",
    image: "images/The RabbitRatMan.png",
    text: [
      "The night of the full moon arrives quietly.",
      "Candlekeep is peaceful. The distant crash of waves against the cliffs below mingles with the occasional creak of timbers and muffled voices from somewhere else in the inn. You retire to your room knowing what tonight may bring. The curse is no secret to you. You have felt it lurking beneath your skin for days now, waiting.",
      "Sleep comes uneasily.",
      "At first, it is only a dream.",
      "You find yourself running through narrow alleyways slick with rain. The air is thick with the scent of smoke, sewage, and something else—something intoxicating. Food. Fear. Prey.",
      "You are not alone.",
      "Hundreds of tiny feet scurry beside you. Countless yellow eyes gleam in the darkness. They do not threaten you. They follow you.",
      "They obey you.",
      "A voice whispers from the shadows.",
      "“Why fear what you are becoming?”",
      "The words echo through the maze of alleys.",
      "“The weak hide behind laws. The strong take what they need.”",
      "The whisper feels familiar. Comforting.",
      "Then the pain begins.",
      "You awaken with a gasp.",
      "Moonlight spills through the window.",
      "Every muscle in your body seizes. Agony tears through your limbs as bones shift and stretch beneath your flesh. Your fingernails split and lengthen into black claws. Your teeth ache before erupting into sharp points.",
      "You try to cry out, but the sound that escapes your throat is not entirely human.",
      "The room spins.",
      "Your senses explode into life.",
      "You can hear the heartbeat of the innkeeper sleeping below. You can smell stale bread from the kitchen, candle wax in the hallway, damp wood beneath the floorboards. Every scent carries meaning. Every sound paints a picture.",
      "And beneath it all...",
      "You smell the rats.",
      "Dozens of them.",
      "Perhaps hundreds.",
      "Within the walls.",
      "Beneath the floor.",
      "Outside in the streets.",
      "You know where they are without seeing them.",
      "You know they know where you are.",
      "For a brief moment, fear threatens to overwhelm you.",
      "Then something changes.",
      "The pain fades.",
      "The hunger remains.",
      "Not hunger for food.",
      "Hunger for control.",
      "For survival.",
      "For advantage.",
      "The feeling settles comfortably into your chest.",
      "The moon hangs high outside your window.",
      "You catch your reflection in the room's small mirror.",
      "Your features are still mostly your own, but not entirely. Your eyes gleam in the darkness. Your smile reveals teeth that seem just a little too sharp.",
      "And somehow, despite everything, you feel stronger than you ever have before.",
      "Faster.",
      "Sharper.",
      "More alive.",
      "As dawn approaches, the transformation recedes, leaving you exhausted but exhilarated.",
      "The curse has taken root.",
      "You sense that this is only the beginning.",
      "Something ancient and cunning now stirs within you, watching through your eyes and listening through your ears.",
      "For now, it is content to wait.",
      "For now, it merely whispers.",
      "And part of you is beginning to listen.",
    ],
  },
  {
    id: "tap-tap-tap",
    title: "Tap tap tap…",
    image: "images/taptaptap.png",
    text: [
      "The night is still.",
      "The inn has long since fallen silent, save for the occasional groan of old timbers and the distant murmur of the sea beyond Candlekeep's walls. Sleep comes easily after the day's travels.",
      "Then something wakes you.",
      "At first, you are not sure what it is.",
      "A faint scratching.",
      "Scratch.",
      "Scratch.",
      "Scratch.",
      "Your eyes open.",
      "Moonlight spills through the window, casting pale silver bars across the floorboards.",
      "The scratching comes again.",
      "Slowly, you sit up.",
      "There, beside your bed, lies a book.",
      "You do not remember placing it there.",
      "The worn leather cover is dark and cracked with age. Strange symbols are embossed into the binding, too faded to identify in the dim light.",
      "Standing beside it is a raven.",
      "The bird watches you with unsettling intelligence.",
      "Its black feathers gleam silver beneath the moonlight.",
      "Scratch.",
      "The raven lowers its head and drags a claw across the book's cover.",
      "Tap.",
      "Tap.",
      "Tap.",
      "It strikes the book with its beak.",
      "Then it looks directly into your eyes.",
      "Waiting.",
      "Expecting.",
      "You glance toward the door.",
      "Toward the window.",
      "No one else is here.",
      "The bird is utterly silent.",
      "The room feels wrong somehow.",
      "Not dangerous.",
      "Significant.",
      "As though the world itself is holding its breath.",
      "The raven taps the book once more.",
      "Slowly, you reach toward it.",
      "The moment your fingers brush the leather cover, a chill races through your arm.",
      "The room vanishes.",
      "For a heartbeat, you stand somewhere else.",
      "A vast library stretches endlessly into darkness.",
      "Shelves tower higher than castle walls.",
      "Books drift through the air like falling leaves.",
      "Whispers echo from every direction.",
      "Thousands of voices speaking words you cannot quite understand.",
      "At the center of the impossible library stands a figure cloaked in shadow.",
      "You cannot see its face.",
      "You cannot tell whether it is man, woman, devil, god, or something older than all of them.",
      "Yet you feel its gaze settle upon you.",
      "A single page tears itself free from one of the floating books and drifts toward you.",
      "Upon it is written a single sentence.",
      "“Knowledge carries a price. The wise choose what they are willing to pay.”",
      "The words burn themselves into your memory.",
      "Then the vision ends.",
      "You find yourself back in your room.",
      "The raven remains where it stood.",
      "Watching.",
      "Waiting.",
      "For the first time, it speaks.",
      "Its voice is little more than a whisper carried on the wind.",
      "“Soon.”",
      "The bird spreads its wings.",
      "A flurry of black feathers fills the room.",
      "When they settle, the raven is gone.",
      "Only the book remains.",
      "Resting silently upon the floor.",
      "Waiting to be opened.",
    ],
  },
  {
    id: "finally-an-answer",
    title: "Finally, an answer…",
    image: "images/answer.png",
    text: [
      "The hours pass unnoticed.",
      "While the others rest, celebrate, or pursue their own interests within Candlekeep's towering halls, you lose yourself among shelves older than kingdoms. Dust gathers on your sleeves. Candle stubs burn low beside stacks of forgotten tomes.",
      "Lycanthropy.",
      "The curse appears again and again throughout your research.",
      "Ancient journals. Temple records. Bestiaries. Personal accounts. Confessions.",
      "Many contradict one another.",
      "Most are incomplete.",
      "Yet certain themes emerge with remarkable consistency.",
      "One evening, long after most of the scribes have retired, you find yourself seated before a collection of texts that have occupied your attention for days.",
      "A frustrating puzzle.",
      "A hundred different theories.",
      "A hundred different remedies.",
      "Silver.",
      "Rare herbs.",
      "Moonlit rituals.",
      "Blood sacrifices.",
      "Pilgrimages.",
      "Theories layered atop theories until truth becomes nearly impossible to distinguish from superstition.",
      "You rub your eyes and return to a weathered volume bound in faded blue leather.",
      "You have already read it twice.",
      "Something compels you to read it a third time.",
      "And then you see it.",
      "A single passage.",
      "Only a few lines long.",
      "So simple that your eyes had skipped over it before.",
      "You read it once.",
      "Then again.",
      "Then a third time.",
      "Your pulse quickens.",
      "The author—a respected priest-scholar from centuries past—describes dozens of cases of lycanthropy. Confirmed cases. Documented cures.",
      "No elaborate ritual.",
      "No rare ingredients.",
      "No hidden secret.",
      "Simply:",
      "“The curse may be ended by the proper application of divine power, most commonly through the spell known as Remove Curse.”",
      "You stare at the page.",
      "Surely it cannot be that simple.",
      "Hours of cross-referencing follow.",
      "One source becomes three.",
      "Three become seven.",
      "Seven become twelve.",
      "Again and again the same conclusion appears.",
      "Remove Curse.",
      "Not difficult.",
      "Not rare.",
      "Not legendary.",
      "Just overlooked.",
      "Buried beneath centuries of rumor and fear.",
      "You lean back in your chair, equal parts triumphant and annoyed.",
      "Entire villages have burned because nobody bothered to check the obvious answer.",
      "You begin gathering notes for your companions.",
      "Then another pattern catches your attention.",
      "One that appears less often.",
      "One that scholars mention only reluctantly.",
      "A phrase repeated across centuries.",
      "Always slightly different.",
      "Always referring to the same thing.",
      "“The cost.”",
      "One account warns:",
      "“Many embrace the gift and discover the cost too late.”",
      "Another notes:",
      "“Strength, resilience, heightened senses—such blessings seldom come freely. The cost remains poorly understood, though its effects are well documented.”",
      "A third simply states:",
      "“Of those who accepted the curse willingly, most eventually paid the cost.”",
      "You continue reading.",
      "The details remain frustratingly vague.",
      "No author fully explains what the cost is.",
      "Some claim it changes a person.",
      "Others suggest it reveals what was already hidden.",
      "Several writers avoid discussing it entirely.",
      "Yet a curious detail emerges.",
      "Every few generations, a name appears.",
      "A hunter.",
      "A guardian.",
      "A wandering hero.",
      "A lycanthrope who carried the curse for years without succumbing to the cost.",
      "Rare.",
      "Exceptionally rare.",
      "But not impossible.",
      "The final text of the evening is a journal written by an elderly priest nearing the end of his life.",
      "Its final entry reads:",
      "“Do not mistake rarity for impossibility. A few have endured the curse without surrendering to the cost. Their victories were hard-won, but they were victories nonetheless.”",
      "You close the book.",
      "The library is silent.",
      "Only the distant crackle of candles remains.",
      "At last, you have your answer.",
      "The cure is real.",
      "The cure is accessible.",
      "And whatever the curse truly offers...",
      "It always carries a cost.",
      "Whether that cost can be resisted remains a question only time can answer.",
    ],
  },
  {
    id: "book-of-the-raven",
    title: "Book of the Raven",
    image: "images/book3.png",
    text: [
      "The Book of the Raven is the firsthand account (written in Common) of an anonymous author who, after falling off her horse and breaking her leg, was rescued and befriended by Vistani travelers who graciously nursed her back to health. The author and her horse traveled with the Vistani for three months, during which the author spent most of her time laid up in a Vistani covered wagon, where she took to writing this book to pass the time. Although a dozen Vistani are colorfully described in the tome, only two are mentioned by name: Drasha, a teenaged girl who applied bandages and poultices to the author's wounded leg, and Darzin, a one-armed boy with a terrible fear of wolves who sang beautiful songs to help the author take her mind off the pain. The book provides a detailed account of the Vistani way of life, with emphasis on their food and music. Their overland journey is also discussed, albeit from the viewpoint of one who spent most of it inside a covered wagon. The author describes rough roads, days of travel through impenetrable mist and thick forest, crackling fires on cold nights,",
      "Vistani:",
      "• The Vistani are planar travelers often encountered in the Shadowfell, and they seem to be immune to the despair that besets all other visitors to that plane. They travel in horse-drawn, barrel-shaped wagons and have no permanent home.",
      "• The Vistani display their wealth openly as a sign of prosperity, sharing their good fortune with friends and strangers alike. Vistani resolve disagreements through contests that end with reconciliatory singing, dancing, and storytelling.",
      "• Vistani families can be big or small, but each family is a gerontocracy, with the oldest member ruling the roost. This elder has most of the responsibility for enforcing traditions, settling disputes, setting the course for the group's travels, and preserving the Vistani way of life.",
      "• The Vistani have the power- some say gift-to travel through the mists that lead to forlorn realms within the Shadowfell known as the Domains of Dread, where creatures born in darkness dwell. This \"gift\" was thrust upon them by mysterious entities called the Dark Powers, as a boon for their kindness toward strangers.",
      "• The Vistani believe that ravens carry lost souls within them. Hence, killing a raven is considered bad luck in Vistani culture.",
    ],
  },
];
